### PR TITLE
Relicense under LGPL v2.1 or later

### LINKED ISSUE #303: Possible incompatibility of license with LAMMPS
librascal is distributed under the LGPL-v3 license, and LAMMPS under the GPL-v2 license. These two licenses are incompatible in the sense that if one redistribute code, they must do so under GPL-v3 license. Since LAMMPS is **not** distributed under `GPL-v2 or later` but `GPL-v2` license, this could make librascal incompatible with LAMMPS from a distribution standpoint (i.e. we could not distribute code using librascal inside the main LAMMPS repository without them changing the license to GPL-v3). For more information on compatibility see https://softwareengineering.stackexchange.com/q/238748.

Since it is much easier for us to change the license to LGPL-v2-or-later than for LAMMPS to change to GPL-v3 (this requires contacting all contributors and ensuring they agree to the license change), this might be a good thing to do on our side 😃.

----

As a side question, was there a reason that a copyleft (GPL/LGPL) license was picked instead of a permissive one (BSD/MIT)? I tend to prefer permissive licenses for libraries since that make them compatible with everything, which is usually the goal. I know some people strongly disagree with this!

### PR DESCRIPTION
**Pull request by Luthaf**
Hi everyone, we would like to re-license this code from the current LGPL-v3-or-later to LGPL-v2.1-or-later, mainly for compatibility reason with LAMMPS which is distributed under GPLv2-only (which is incompatible with librascal current license according to the FSF itself: https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility).

This is only possible if everyone who has code in the library explicitly agree, so this PR will be used to collect agreement from all contributors. Please answer below with "I agree to relicense to LGPL-v2.1-or-later" or a similar comment if you agree!

- [x] @agoscinski, commits as "Alexander Goscinski", "Alexander Jan Goscinski", "agoscinski", "alexgo"
- [x] @cbenmahm ; commits as "Chiheb Ben Mahmoud"
- [x] @felixmusil, commits as "Félix", "felixmusil", "musil"
- [x] @Luthaf, commits as "Guillaume Fraux", "Luthaf"
- [x] @curiosity54, commits as "Jigyasa Nigam"
- [x] @kvhuguenin, commits as "Kevin Huguenin", "kvhuguenin"
- [x] @Klimkou, commits as "Klimkou"
- [x] @Lgigli2190, commits as "Lorenzo Gigli"
- [x] @mastricker, commits as "Markus Stricker", "mastricker"
- [x] @max-veit, commits as "Max Veit"
- [x] @mjwillatt, commits as "Michael Willatt"
- [x] @ceriottm, commits as "Michele Ceriotti"
- [x] @rosecers, commits as "Rose Cersonsky", "rosecers"
- [x] @tjunge, commits as "Till Junge"
- [x] @andreagrisafi, commits as "andrea.grisafi"
- [x] @bhelfrecht, commits as "bhelfrecht"
- [x] @gibertif, commits as "fede", "gibertif"
- [x] @giulioi, commits as "giulioi"

----

Fixes #303

### CODE REVIEW

**Comment by Luthaf** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by ceriottm** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by curiosity54** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by andreagrisafi** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by felixmusil** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by rosecers** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by lgigli** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by max-veit** [comment]
I, too, agree to relicense to LGPL-v2.1or-later.

**Comment by mastricker** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by bhelfrecht** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by agoscinski** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by cbenmahm** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by kvhuguenin** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by gibertif** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by giulioi** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by Klimkou** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Comment by agoscinski** [comment]
@mjwillatt cannot access his github account, so he wrote to @ceriottm and me an email.


>Dear Alex,
>
>I agree to relicense (cosmo-epfl) librascal to LGPL-v2.1-or-later.
>
>Michael Willatt

**Comment by tjunge** [comment]
I agree to relicense to LGPL-v2.1-or-later

**Review by agoscinski — APPROVED** [review]
It looks fine

**Comment by Luthaf** [comment]
Thanks everyone for accepting to relicense this!

**Pull request merged**
